// AUTO-GENERATED by scripts/gen-poseidon-constants.mjs — do not edit by hand.
// poseidon255 round constants and MDS matrices for state sizes t = 2, 3, 4 (BLS12-381 Fr).

export declare const POSEIDON_C: Record<number, bigint[]>;
export declare const POSEIDON_M: Record<number, bigint[][]>;
