// Verifies the TS Poseidon port against vectors generated by the Rust `noterail` (soroban-poseidon).
// Run: npx tsx scripts/verify-poseidon.ts   (or: pnpm --filter @noir-rail/sdk verify:poseidon)
import { poseidon } from "../src/poseidon.ts";

type Vec = { name: string; inputs: bigint[]; expected: bigint };

const vectors: Vec[] = [
  // Vector A — precommitment = Poseidon(nullifier, secret)
  {
    name: "A.precommitment (t=3)",
    inputs: [1645523975n, 843740978n],
    expected:
      50021912042164852881645144355939846232990834278820097157412375185363546655785n,
  },
  // Vector A — commitment = Poseidon(value, label, precommitment)
  {
    name: "A.commitment (t=4)",
    inputs: [
      123456789n,
      41326900859765916281495261270783062340637983989630258703078194829572341339044n,
      50021912042164852881645144355939846232990834278820097157412375185363546655785n,
    ],
    expected:
      29922890138611366191895508977959615069644902447257865503931076055660429141579n,
  },
  // Vector B
  {
    name: "B.precommitment (t=3)",
    inputs: [158504937n, 771550293n],
    expected:
      7927601997034392490294453765679195811342637747542092830437254394212592250710n,
  },
  {
    name: "B.commitment (t=4)",
    inputs: [
      123456789n,
      18761852945523753919913435238346834045829994958717724683765813125778461783066n,
      7927601997034392490294453765679195811342637747542092830437254394212592250710n,
    ],
    expected:
      47486172325000505281286574716591953850386273116726349567472152337564924504887n,
  },
];

let allPass = true;
for (const v of vectors) {
  const got = poseidon(v.inputs);
  const ok = got === v.expected;
  allPass &&= ok;
  console.log(`${ok ? "PASS" : "FAIL"}  ${v.name}`);
  if (!ok) {
    console.log(`   expected ${v.expected}`);
    console.log(`   got      ${got}`);
  }
}
console.log(allPass ? "\n✓ all poseidon vectors match" : "\n✗ poseidon mismatch");
process.exit(allPass ? 0 : 1);
